server:
  port: 8087


spring:
  application:
    name: Springbootplay


  data:
    mongodb:
      host: localhost
      port: 27017
      database: test


springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui-akhil.html
    enabled: true

#logging:
#  level:
#    ROOT: ERROR